# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-12-15 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0002_auto_20171214_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='celular',
            field=models.IntegerField(),
        ),
    ]
