# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-12-15 02:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0004_auto_20171214_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='celular',
            field=models.BigIntegerField(default=3104797832, validators=[django.core.validators.MinValueValidator(3000000000, b'asd'), django.core.validators.MaxValueValidator(3999999999, b'message')]),
            preserve_default=False,
        ),
    ]
